[project]
name = "tetris"
version = "0.1.0"
description = "A tetris game made with love using pygame"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "py-make>=0.1.2",
    "pygame>=2.6.1",
]
